"use client";

import Link from "next/link";
import { motion } from "framer-motion";
import { Shield, Lock, Zap, ArrowRight, TrendingUp, Users, Clock, Fingerprint, Layers, ChevronDown } from "lucide-react";
import BackgroundParticles from "@/components/BackgroundParticles";

const stats = [{icon:Shield,value:"AES-256",label:"GCM Encryption"},{icon:Lock,label:"HMAC-SHA256",value:"Integrity"},{icon:Layers,label:"Two-Layer",value:"Security"},{icon:TrendingUp,label:"Real-time",value:"Processing"}];
const steps = [{icon:Users,title:"Register",desc:"Verify NID with bank officer. K1 key generated via HMAC-SHA256, bound to your identity."},{icon:Lock,title:"Encrypt",desc:"M + F1 encrypted with AES-256-GCM. Key from K2 + secret + timestamp T via HKDF."},{icon:Zap,title:"Transact",desc:"Server decrypts, verifies HMAC, checks replay via T version, processes atomically."}];
const feats = [{icon:Fingerprint,title:"K1 - Identity Key",desc:"K1=HMAC(act_code,NID||browser_fp). Never stored plaintext. Re-computed at runtime."},{icon:Clock,title:"Rolling Timestamp T",desc:"T updated via HMAC chain after each tx. Replays carry stale version - rejected."},{icon:Shield,title:"Dual Integrity",desc:"GCM auth tag + HMAC-SHA256 F1. Two independent integrity checks."},{icon:Layers,title:"TLS 1.3 + App Crypto",desc:"Nginx TLS 1.3 at edge. AES-256-GCM inside. Two layers even within TLS tunnel."}];

export default function LandingPage() {
  return (<div className="bg-surface text-white overflow-hidden relative">
    <BackgroundParticles />
    <section className="relative min-h-screen flex items-center justify-center overflow-hidden"><div className="absolute inset-0 bg-[radial-gradient(circle_at_50%_0%,rgba(239,68,68,0.08),transparent_50%),radial-gradient(circle_at_80%_80%,rgba(245,158,11,0.05),transparent_50%)]" />
      <div className="relative z-10 text-center px-6 max-w-4xl mx-auto">
        <motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{duration:.8}}><div className="inline-flex items-center gap-2 bg-white/[0.02] backdrop-blur-sm rounded-full px-4 py-2 mb-8 border border-red-500/15"><Shield className="w-4 h-4 text-red-400"/><span className="text-sm text-white/30">ICECTE 2022 - E-Payment Security Framework</span></div></motion.div>
        <motion.h1 initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.1}} className="text-5xl sm:text-6xl lg:text-7xl font-bold leading-tight mb-6">Digital Payments,<br/><span className="text-gradient-red">Bulletproof Security</span></motion.h1>
        <motion.p initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.2}} className="text-lg sm:text-xl text-white/25 max-w-2xl mx-auto mb-10">AES-256-GCM encrypted transactions. HMAC-SHA256 integrity. TLS 1.3 at transport. Two-layer security model.</motion.p>
        <motion.div initial={{opacity:0,y:30}} animate={{opacity:1,y:0}} transition={{delay:.3}} className="flex flex-col sm:flex-row items-center justify-center gap-4">
          <Link href="/login"><motion.button whileHover={{scale:1.05}} whileTap={{scale:.95}} className="btn-red px-8 py-4 text-lg flex items-center gap-3">Get Started <ArrowRight className="w-5 h-5"/></motion.button></Link>
          <Link href="#how"><motion.button whileHover={{scale:1.05}} whileTap={{scale:.95}} className="btn-ghost px-6 py-4 text-lg flex items-center gap-2">How It Works <ChevronDown className="w-5 h-5"/></motion.button></Link>
        </motion.div>
        <motion.div initial={{opacity:0,y:40}} animate={{opacity:1,y:0}} transition={{delay:.5}} className="mt-16 grid grid-cols-2 sm:grid-cols-4 gap-4">{stats.map((s,i)=>(<div key={i} className="glass p-4 group hover:border-red-500/10 transition-all"><s.icon className="w-6 h-6 text-red-400 mx-auto mb-2"/><p className="text-lg font-bold text-white">{s.value}</p><p className="text-xs text-white/20">{s.label}</p></div>))}</motion.div>
      </div>
      <motion.div animate={{y:[0,8,0]}} transition={{duration:2,repeat:Infinity}} className="absolute bottom-8 left-1/2 -translate-x-1/2 text-white/10"><ChevronDown className="w-6 h-6"/></motion.div>
    </section>
    <section id="how" className="py-24 bg-surface-1"><div className="max-w-6xl mx-auto px-6"><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="text-center mb-16"><h2 className="text-4xl font-bold text-white mb-4">How E-Pay Works</h2><p className="text-lg text-white/25 max-w-2xl mx-auto">Three steps from registration to encrypted transaction.</p></motion.div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{steps.map((s,i)=>(<motion.div key={i} initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.15}} className="glass p-8 group hover:border-red-500/10"><div className="w-14 h-14 bg-gradient-to-br from-red-600 to-red-500 rounded-2xl flex items-center justify-center mb-6 group-hover:scale-110 transition-transform shadow-lg shadow-red-500/15"><s.icon className="w-7 h-7 text-white"/></div><div className="inline-flex px-2.5 py-1 rounded-full bg-red-500/5 text-red-400 text-xs font-bold mb-3 border border-red-500/10">Step {i+1}</div><h3 className="text-xl font-bold text-white mb-3">{s.title}</h3><p className="text-sm text-white/25">{s.desc}</p></motion.div>))}</div></div></section>
    <section className="py-24"><div className="max-w-6xl mx-auto px-6"><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}} className="text-center mb-16"><h2 className="text-4xl font-bold text-white mb-4">Security by Design</h2><p className="text-lg text-white/25">K1 for identity. K2 for encryption. T for anti-replay.</p></motion.div><div className="grid grid-cols-1 sm:grid-cols-2 gap-6">{feats.map((f,i)=>(<motion.div key={i} initial={{opacity:0,y:20}} whileInView={{opacity:1,y:0}} viewport={{once:true}} transition={{delay:i*.1}} className="glass p-6 group hover:border-red-500/10"><div className="flex items-start gap-4"><div className="w-12 h-12 bg-red-500/5 rounded-xl flex items-center justify-center border border-red-500/10 group-hover:scale-110 transition-transform"><f.icon className="w-6 h-6 text-red-400"/></div><div><h3 className="font-bold text-white mb-2">{f.title}</h3><p className="text-sm text-white/25">{f.desc}</p></div></div></motion.div>))}</div></div></section>
    <section className="py-24 bg-surface-1"><div className="max-w-4xl mx-auto px-6 text-center"><motion.div initial={{opacity:0,y:30}} whileInView={{opacity:1,y:0}} viewport={{once:true}}><h2 className="text-4xl font-bold text-white mb-4">Ready to Go Cashless?</h2><p className="text-lg text-white/25 mb-8">Secure, fast, built on proven cryptographic framework.</p><Link href="/login"><motion.button whileHover={{scale:1.05}} whileTap={{scale:.95}} className="btn-red px-8 py-4 text-lg flex items-center gap-3 mx-auto">Sign In Now <ArrowRight className="w-5 h-5"/></motion.button></Link></motion.div></div></section>
    <footer className="border-t border-border py-12 text-center text-sm"><div className="flex items-center justify-center gap-3 mb-4"><Shield className="w-5 h-5 text-red-400"/><span className="text-white font-bold text-lg">E-<span className="text-red-500">Pay</span></span></div><p className="text-white/15">Framework from ICECTE 2022. Extended with TLS 1.3.</p></footer>
  </div>);
}
