"use client";

import { useState } from "react";
import { useRouter } from "next/navigation";
import { motion } from "framer-motion";
import { Shield, Lock, Wallet, ArrowRight, Loader2 } from "lucide-react";
import { toast } from "sonner";
import BackgroundParticles from "@/components/BackgroundParticles";

export default function LoginPage() {
  const r=useRouter(); const [u,setU]=useState(""); const [p,setP]=useState(""); const [ld,setLd]=useState(false);
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setLd(true);try{const f=await fetch("/api/auth/login",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({username:u,password:p})});const d=await f.json();if(f.ok){toast.success("Welcome back!");r.push("/dashboard");r.refresh()}else toast.error(d.error||"Login failed")}catch{toast.error("Network error")}finally{setLd(false)}};

  return (<div className="min-h-screen flex bg-surface relative">
    <BackgroundParticles />
    <div className="hidden lg:flex lg:w-1/2 bg-surface-1 relative overflow-hidden border-r border-border"><div className="absolute inset-0 bg-[radial-gradient(circle_at_top_right,rgba(239,68,68,0.06),transparent_50%),radial-gradient(circle_at_bottom_left,rgba(245,158,11,0.03),transparent_50%)]" /><motion.div initial={{opacity:0,y:20}} animate={{opacity:1,y:0}} transition={{duration:.8}} className="relative z-10 flex flex-col justify-center px-16 text-white"><div className="flex items-center gap-3 mb-8"><div className="w-12 h-12 bg-gradient-to-br from-red-600 to-red-500 rounded-xl flex items-center justify-center shadow-lg shadow-red-500/15"><Shield className="w-7 h-7 text-white"/></div><span className="text-2xl font-bold">E-<span className="text-red-500">Pay</span></span></div><h1 className="text-5xl font-bold leading-tight mb-6">Secure Digital<br/><span className="text-red-400">Payments</span></h1><p className="text-white/25 text-lg max-w-md">Bank-grade encryption. AES-256-GCM and HMAC-SHA-256 protection.</p><div className="mt-12 flex gap-8"><div className="flex items-center gap-3"><div className="w-10 h-10 bg-white/[0.03] rounded-lg flex items-center justify-center border border-border"><Lock className="w-5 h-5 text-red-400"/></div><div><p className="font-semibold">TLS 1.3</p><p className="text-sm text-white/20">Transport Layer</p></div></div><div className="flex items-center gap-3"><div className="w-10 h-10 bg-white/[0.03] rounded-lg flex items-center justify-center border border-border"><Wallet className="w-5 h-5 text-red-400"/></div><div><p className="font-semibold">AES-256</p><p className="text-sm text-white/20">Application Layer</p></div></div></div></motion.div></div>
    <div className="flex-1 flex items-center justify-center p-8 relative z-10"><motion.div initial={{opacity:0,x:20}} animate={{opacity:1,x:0}} transition={{duration:.6,delay:.2}} className="w-full max-w-md"><div className="text-center mb-10"><h2 className="text-3xl font-bold text-white mb-2">Welcome back</h2><p className="text-white/25">Enter your credentials to access your account</p></div><form onSubmit={submit} className="space-y-5"><div><label className="block text-sm font-semibold text-white/30 mb-2">Username</label><input type="text" value={u} onChange={e=>setU(e.target.value)} placeholder="e.g. alice" required className="input-dark w-full px-4 py-3.5"/></div><div><label className="block text-sm font-semibold text-white/30 mb-2">Password</label><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="Enter your password" required className="input-dark w-full px-4 py-3.5"/></div><motion.button whileHover={{scale:1.02}} whileTap={{scale:.98}} type="submit" disabled={ld} className="btn-red w-full py-3.5 flex items-center justify-center gap-2 disabled:opacity-50">{ld?<Loader2 className="w-5 h-5 animate-spin"/>:<><ArrowRight className="w-5 h-5"/>Sign in</>}</motion.button></form><div className="mt-8 p-4 bg-white/[0.02] rounded-xl border border-border"><p className="text-sm text-white/30 mb-1">Demo Credentials</p><p className="text-sm text-white/15">alice / alice123  |  bob / bob456</p></div></motion.div></div>
  </div>);
}
