"""initial schema

Revision ID: b0a38563f880
Revises: 
Create Date: 2026-05-22 16:48:36.761649

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b0a38563f880'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('accounts_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('event_detail',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_index('idx_audit_log_event_type')
        batch_op.drop_index('idx_audit_log_occurred_at')
        batch_op.drop_index('idx_audit_log_user_id')

    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.alter_column('registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('device_credentials_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('timestamp_keys', schema=None) as batch_op:
        batch_op.alter_column('last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('timestamp_keys_user_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'users', ['user_id'], ['user_id'])

    with op.batch_alter_table('tls_certificates', schema=None) as batch_op:
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.drop_constraint('tls_certificates_device_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'device_credentials', ['device_id'], ['device_id'])

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('status',
               existing_type=postgresql.ENUM('pending', 'completed', 'failed', 'rejected', name='transaction_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::transaction_status"))
        batch_op.alter_column('initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ip_address',
               existing_type=postgresql.INET(),
               type_=sa.String(length=45),
               existing_nullable=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_status',
               existing_type=postgresql.ENUM('active', 'suspended', 'locked', 'pending', name='account_status'),
               type_=sa.String(length=20),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::account_status"))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=True,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('account_status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('active', 'suspended', 'locked', 'pending', name='account_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'active'::account_status"))

    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
        batch_op.alter_column('initiated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('status',
               existing_type=sa.String(length=20),
               type_=postgresql.ENUM('pending', 'completed', 'failed', 'rejected', name='transaction_status'),
               existing_nullable=False,
               existing_server_default=sa.text("'pending'::transaction_status"))

    with op.batch_alter_table('tls_certificates', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('tls_certificates_device_id_fkey', 'device_credentials', ['device_id'], ['device_id'], ondelete='CASCADE')
        batch_op.alter_column('issued_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('timestamp_keys', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('timestamp_keys_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('last_updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('device_credentials', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('device_credentials_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')
        batch_op.alter_column('registered_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.create_index('idx_audit_log_user_id', ['user_id'], unique=False)
        batch_op.create_index('idx_audit_log_occurred_at', [sa.text('occurred_at DESC')], unique=False)
        batch_op.create_index('idx_audit_log_event_type', ['event_type'], unique=False)
        batch_op.alter_column('occurred_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('ip_address',
               existing_type=sa.String(length=45),
               type_=postgresql.INET(),
               existing_nullable=True)
        batch_op.alter_column('event_detail',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)

    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('accounts_user_id_fkey', 'users', ['user_id'], ['user_id'], ondelete='RESTRICT')
        batch_op.alter_column('updated_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))
        batch_op.alter_column('created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               nullable=False,
               existing_server_default=sa.text('now()'))

    # ### end Alembic commands ###
